<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Ricento
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2014 Diglin (http://www.diglin.com)
 */
/* @var $this Mage_Adminhtml_Block_Template */
?>
<div class="ricento_dashboard">
    <div class="left">
    <?php echo $this->getChild('ricento.dashboard.left'); ?>
    </div>
    <div class="right">
    <?php echo $this->getChild('ricento.dashboard.right'); ?>
    </div>
</div>