<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Mage_Adminhtml_Block_Template */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('ricardo.ch - Dashboard') ?></h3></td>
        </tr>
    </table>
</div>
<div class="ricento_dashboard">
    <div class="left">
    <?php echo $this->getChildHtml('ricento.dashboard.left'); ?>
    </div>
    <div class="right">
    <?php echo $this->getChildHtml('ricento.dashboard.right'); ?>
    </div>
</div>