<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author      Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @see Diglin_Ricento_Adminhtml_AccountController */
?>
<div class="content-header" style="visibility: visible;">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width: 50%;">
                    <h3 class="icon-head head-categories"><?php echo $this->getTitle() ?></h3>
                    <?php echo Mage::helper('diglin_ricento')->__('You may also access to the %s content of this page</a> in a new window.',
                        '<a href="'. $this->getIframeUrl() .'" target="_blank" onClick="javascript:document.getElementById(\'dashboarddiv\').innerHTML=\'\'; ">'); ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div id="dashboarddiv" style="margin-top: -18px">
    <iframe style="border-bottom:3px solid #dfdfdf" id="dashboardiframe" frameborder="0"
        src="<?php echo $this->getIframeUrl() ?>" height="960px" width="100%"></iframe>
</div>
<script>
    function GetHeight() {
        var y = 0;
        if (self.innerHeight) {
            y = self.innerHeight;
        } else if (document.documentElement && document.documentElement.clientHeight) {
            y = document.documentElement.clientHeight;
        } else if (document.body) {
            y = document.body.clientHeight;
        }
        return y;
    }

    function doResize() {
        document.getElementById("dashboardiframe").style.height = (GetHeight() - 220) + "px";
    }

    window.onresize = doResize;
    doResize();
</script>