<?php
/**
 * ricardo.ch AG - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2014 ricardo.ch AG (http://www.ricardo.ch)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>{{pdf_row_separator}}

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<?php if (isset($_specificInfo['bid_ids'])): ?>
<?php echo Mage::helper('diglin_ricento')->__('Transactions %s', $_specificInfo['bid_ids']) ?>
<?php endif; ?>
<?php foreach ($_specificInfo['methods'] as $_value):?>
    <?php echo $_value ?>{{pdf_row_separator}}
<?php endforeach; ?>
<?php if (isset($_specificInfo['information'])): ?>
    <?php echo $_specificInfo['information']; ?>{{pdf_row_separator}}
<?php endif; ?>

<?php endif;?>

<?php echo implode($this->getChildPdfAsArray(), '{{pdf_row_separator}}') ?>