<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @category    Ricento
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2014 Diglin (http://www.diglin.com)
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Best Sellers') ?></h4></div>
    <fieldset class="np">
        <?php echo $this->getChildHtml('ricento.dashboard.bestsellers.grid'); ?>
    </fieldset>
</div>