<?php
/**
 * ricardo.ch AG - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2014 ricardo.ch AG (http://www.ricardo.ch)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $this Diglin_Ricento_Block_Adminhtml_Dashboard_Lifetime */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('ricardo.ch Lifetime Sales') ?></h4></div>
    <fieldset class="a-center bold">
        <span class="nowrap" style="font-size:18px;"><span class="price"><?php echo $this->getValueHtml() ?></span><span style="font-size:14px; color:#686868;"></span></span>
    </fieldset>
</div>