<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @category    Ricento
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2014 Diglin (http://www.diglin.com)
 */

/** @var $this Diglin_Ricento_Block_Adminhtml_Dashboard_Lifetime */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('ricardo.ch Lifetime Sales') ?></h4></div>
    <fieldset class="a-center bold">
        <span class="nowrap" style="font-size:18px;"><span class="price"><?php echo $this->getValueHtml() ?></span><span style="font-size:14px; color:#686868;"></span></span>
    </fieldset>
</div>