<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @category    Ricento
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2014 Diglin (http://www.diglin.com)
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Turnover per month') ?></h4></div>
    <fieldset class="a-center bold">
        <?php echo $this->getChildHtml('ricento.dashboard.turnover.graph'); ?>
    </fieldset>
</div>