<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Turnover per month') ?></h4></div>
    <fieldset class="a-center bold">
        <?php echo $this->getChildHtml('ricento.dashboard.turnover.graph'); ?>
    </fieldset>
</div>