<?php
/**
 * ricardo.ch AG - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2014 ricardo.ch AG (http://www.ricardo.ch)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Turnover per month') ?></h4></div>
    <fieldset class="a-center bold">
        <?php echo $this->getChildHtml('ricento.dashboard.turnover.graph'); ?>
    </fieldset>
</div>