<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @var $this Mage_Payment_Block_Info
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>:

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<?php if (isset($_specificInfo['bid_ids'])): ?>
<div class="ricardo-payment-info">
<p><?php echo Mage::helper('diglin_ricento')->__('Transactions: <strong>%s</strong>', $_specificInfo['bid_ids']) ?></p>
<?php endif; ?>
<ul>
    <li><?php echo implode(' / ', $_specificInfo['methods']) ?></li>
    <?php if (isset($_specificInfo['information'])): ?><li><?php echo $_specificInfo['information']; ?></li><?php endif; ?>
</ul>
</div>
<?php endif;?>

<?php echo $this->getChildHtml()?>
