<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Ricento
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2014 Diglin (http://www.diglin.com)
 */
/**
 * @var $this Diglin_Ricento_Block_Adminhtml_Notifications
 */
$helperData = Mage::helper('diglin_ricento');

//@todo get the validation url from the API
$validationUrl = '#';
?>
<?php if ($helperData->isConfigured() && $this->helper('diglin_ricento/api')->isApiTokenCredentialGoingToExpire()): ?>
<div class="notification-global">
    <strong><?php echo $this->__('Your Ricardo API token credentials are going to expire in %s days.', $helperData->getExpirationNotificationDelay());?></strong>
    <?php echo $this->__(' You have to authorize your account to get access to the Ricardo API thanks to the <a href="%s">Ricardo Authorization Page</a>. If you don\'t do it, your Ricardo extension and all related transactions with Ricardo will be blocked. If you want to change this behavior, please <a href="%s">configure</a> the option \'Automatize API Authorization\'',
            $validationUrl,
            $helperData->getConfigurationUrl()); ?>
</div>
<?php endif ?>
