<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var $this Diglin_Ricento_Block_Adminhtml_Notifications_Default
 */
$helperData = Mage::helper('diglin_ricento');
?>
<?php if (!$helperData->isConfigured()): ?>
<div class="notification-global">
    <strong><?php echo $this->__('The Official ricardo.ch Extension has been installed.') ?></strong>
    <?php echo $this->__('Please, click <a href="%s">here to configure</a> the access to the ricardo.ch API.', $helperData->getConfigurationUrl()); ?>
</div>
<?php endif ?>