<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Ricento
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2014 Diglin (http://www.diglin.com)
 */
/**
 * @var $this Diglin_Ricento_Block_Adminhtml_Notifications
 */
$helperData = Mage::helper('diglin_ricento');
?>
<?php if (!$this->helper('diglin_ricento')->isConfigured()): ?>
<div class="notification-global">
    <strong><?php echo $this->__('The Official Ricardo Extension has been installed.') ?></strong>
    <?php echo $this->__('Please, click <a href="%s">here to configure</a> the access to the Ricardo API.', $helperData->getConfigurationUrl()); ?>
</div>
<?php endif ?>