<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var $this Diglin_Ricento_Block_Adminhtml_Notifications_Expiration
 */

/* @var $website Mage_Core_Model_Website */
$website = Mage::app()->getWebsite();
// @fixme real multi website support - planned if needs come
//$websites = Mage::app()->getWebsites();
//foreach ($websites as $website) {
?>
<?php if ($this->getApiReady()): ?>
<div class="notification-global">
    <?php if ($this->isApiCredentialTokenExist($website)): ?>
    <strong><?php echo $this->__('Your ricardo.ch API token credentials are going to expire in %s days for the website "%s".', $this->getExpirationNotificationDelay(), $website->getName());?></strong>
    <?php else: ?>
    <strong><?php echo $this->__('No ricardo.ch API Authorization have been found for the website "%s".', $website->getName());?></strong>
    <?php endif; ?>
    <?php
        $validationUrl = $this->getValidationUrl($website);
        if (empty($validationUrl)) {
            echo Mage::helper('diglin_ricento')->__('Security error occurred with the ricardo API. Please, check your log files.');
        } else {
            echo $this->__('You have to authorize your account to get access to the ricardo.ch API thanks to the <a href="%s">ricardo.ch Authorization Page</a>. If you don\'t do it, your ricardo.ch extension and all related transactions with ricardo.ch will be blocked.',
            $validationUrl); ?>
        <?php } ?>
    <?php echo $this->__('To hide this message, you have to <a href="%s">disable the extension</a>.', Mage::helper('diglin_ricento')->getConfigurationUrl($website)); ?>
</div>
<?php endif ?>
<?php //} ?>