<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Ricento
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2011-2014 Diglin (http://www.diglin.com)
 */
/**
 * @var $this Diglin_Ricento_Block_Adminhtml_Notifications_Expiration
 */

/* @var $website Mage_Core_Model_Website */
foreach ($this->getWebsiteCollection() as $website) :
    $store = $website->getDefaultStore();
?>
    <?php if ($this->isEnabled($store) && $this->isApiConfigured($store) && $this->isApiGoExpire($store)): ?>
    <div class="notification-global">
        <?php if ($this->isApiCredentialTokenExist($store)): ?>
        <strong><?php echo $this->__('Your Ricardo API token credentials are going to expire in %s days for the website "%s".', $this->getExpirationNotificationDelay(), $website->getName());?></strong>
        <?php else: ?>
        <strong><?php echo $this->__('No Ricardo API Authorization have been found for the website "%s".', $website->getName());?></strong>
        <?php endif; ?>
        <?php echo $this->__(' You have to authorize your account to get access to the Ricardo API thanks to the <a href="%s">Ricardo Authorization Page</a>. If you don\'t do it, your Ricardo extension and all related transactions with Ricardo will be blocked.',
                $this->getValidationUrl($store)); ?>
        <?php echo $this->__('To hide this message, you have to <a href="%s">disable the extension</a> for this website.', Mage::helper('diglin_ricento')->getConfigurationUrl()); ?>
    </div>
    <?php endif ?>
<?php endforeach; ?>