<?php
/**
 * ricardo.ch AG - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2014 ricardo.ch AG (http://www.ricardo.ch)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Diglin_Ricento_Block_Adminhtml_Products_Category_Children */
$level = $this->getLevel();
?>
<nav class="span<?php echo $level?> navCat" id=navCatLvl<?php echo $level?>>
<ul class="nav nav-list">
<?php foreach ($this->getCategories() as $category): ?>
    <li class="<?php if ($category->getIsFinal()): ?>final<?php endif; ?><?php if ($this->getSelectedCategoryId() == $category->getId()): ?> selected<?php endif; ?>" >
        <a href="#"
           data-category-id="<?php echo $category->getId(); ?>"
           data-update-prefix = "navCatLvl"
           data-level = "<?php echo $level; ?>"
           data-update-level = "<?php echo $level + 1; ?>"
           data-is-final = "<?php echo $category->getIsFinal(); ?>"
           data-text = "<?php echo $category->getCategoryName(); ?>">
            <?php if (!$category->getIsFinal()): ?>
                <strong class="icon icon-plus">&gt;</strong>
            <?php else: ?>
                <strong class="icon icon-check">&nbsp;</strong>
                <input type="radio" name="ricardo_category_id" id="ricardo_category_id<?php echo $category->getId(); ?>"
                       value="<?php echo $category->getId(); ?>"
                       <?php if ($this->getSelectedCategoryId() == $category->getId()): ?>checked="checked"<?php endif; ?>/>
            <?php endif; ?>
            <div>
                <?php echo $category->getCategoryName(); ?>
            </div>
        </a>
    </li>
<?php endforeach; ?>
</ul>
</nav>