<?php
/* @var $this Diglin_Ricento_Block_Adminhtml_Products_Category_Mapping */
?>
<style>

</style>

<div id="ricardo_categories" <?php if ($this->shouldResize()): ?>class="ricardo_categories_resized"<?php endif; ?>>
<form action="#" onsubmit="Ricento.categoryMappingTargetInput.value = this.serialize(true)['ricardo_category_id']; Ricento.closePopup(); return false;">
    <div class="form-buttons">
        <button type="button" onclick="Ricento.closePopup()" class="cancel button" id="ricardo_categories_button_cancel"><span><?php echo $this->__('Cancel'); ?></span></button>
        <button type="submit" class="save button" id="ricardo_categories_button_save"><span><?php echo $this->__('Confirm');?></span></button>
    </div>
<?php
    echo $this->getChildHtml('toplevel');
?>
    <div id="ricardo_children">
<?php
    echo $this->getChildHtml('sublevel');
?>
    </div>
    <div class="form-buttons">
        <button type="button" onclick="Ricento.closePopup()" class="cancel button" id="ricardo_categories_button_cancel"><span><?php echo $this->__('Cancel'); ?></span></button>
        <button type="submit" class="save button" id="ricardo_categories_button_save"><span><?php echo $this->__('Confirm');?></span></button>
    </div>
</form>
</div>

<script type="text/javascript">
    new Ricento.CategoryMappper({
        wrapperElement : 'ricardo_categories',
        loadChildrenUrl : '<?php echo $this->getUrl('ricento/products_category/children', array('id' => '#ID#', 'level' => '#LVL#')); ?>'
    });
</script>