<?php
/* @var $this Diglin_Ricento_Block_Adminhtml_Products_Category_Mapping */
?>
<style>
    #ricardo_categories {
    }
    #ricardo_categories nav {
        width: 200px;
        float: left;
        margin-right: 10px;
        background-color: rgba(255,255,255,0.7);
    }
    #ricardo_categories li > a {
        display: block;
        padding: 5px;
        border-bottom: 1px solid #333;
        text-decoration: none;
        color: #333;
    }
    #ricardo_categories .selected a {
        background: darkorange;
        color: white;
        font-weight: bold;
    }
    #ricardo_categories input[type="radio"] {
        float: right;
    }
    #ricardo_categories .icon-plus {
        background: url('<?php echo $this->getSkinUrl('images/accordion_open.png')?>') no-repeat;
        width: 16px;
        height: 17px;
        float: right;
        text-indent: -9999px;
    }
    #ricardo_categories .form-buttons {
        clear: both;
        text-align: right;
    }
</style>

<div id="ricardo_categories">
<form action="#" onsubmit="Ricento.categoryMappingTargetInput.value = this.serialize(true)['ricardo_category_id']; Ricento.closePopup(); return false;">
<?php
    echo $this->getChildHtml('toplevel');
?>
    <div id="ricardo_children">
<?php
    echo $this->getChildHtml('sublevel');
?>
    </div>
    <div class="form-buttons">
        <button type="button" onclick="Ricento.closePopup()" class="cancel button" id="ricardo_categories_button_cancel"><span><?php echo $this->__('Cancel'); ?></span></button>
        <button type="submit" class="save button" id="ricardo_categories_button_save"><span><?php echo $this->__('Confirm');?></span></button>
    </div>
</form>
</div>

<script type="text/javascript">
    new Ricento.CategoryMappper({
        wrapperElement : 'ricardo_categories',
        loadChildrenUrl : '<?php echo $this->getUrl('ricento/products_category/children', array('id' => '#ID#', 'level' => '#LVL#')); ?>'
    });
</script>