<?php
/**
 * Scripts for modal popups
 */
/* @var $this Diglin_Ricento_Block_Adminhtml_Products_Listing_Scripts */
?>
<script type="text/javascript">
    Ricento = window.Ricento || {};
<?php if ($this->getListing()): ?>
    Ricento.addProductsPopup = function() {
        var url = '<?php echo $this->getAddProductsPopupUrl() ?>';
        if ($('ricento_popup') && typeof(Windows) != 'undefined') {
            Windows.focus('ricento_popup');
            return;
        }

        Dialog.info({url:url}, {
            closable:true,
            resizable:true,
            maximizable: true,
            draggable:true,
            className:'magento',
            windowClassName:'popup-window',
            title:'Add Product',
            top:50,
            width:900,
            height:600,
            zIndex:1000,
            recenterAuto:false,
            hideEffect:Element.hide,
            showEffect:Element.show,
            id:'ricento_popup',
            showProgress:true,
            onShow:function(dialog) {
                dialog.element.innerHTML.evalScripts();
                /*
                 * products_listing_add_massactionJsObject was declared in local scope, we need to make it global:
                 */
                window.products_listing_add_massactionJsObject = products_listing_addJsObject.massaction;
            }
        });
    };
<?php endif; ?>
    Ricento.addListingPopup = function() {
        alert('TODO');
        //TODO IMPLEMENT
    };
    Ricento.closePopup = function() {
        Windows.close('ricento_popup');
    };
</script>