<?php
/**
 * ricardo.ch AG - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2014 ricardo.ch AG (http://www.ricardo.ch)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Diglin_Ricento_Block_Adminhtml_Products_Listing_Item_Edit_Form */ ?>
<div class="entry-edit">
    <?php echo $this->getTabsHtml(); ?>
    <?php echo $this->getFormHtml(); ?>
</div>
<?php echo $this->getChildHtml('form_after');?>
